/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaCadastros;

import java.sql.SQLException;
import tabelas.Bank;
import tabelas.CadMunic;
import tabelas.Contas;
import tabelas.ContasTipo;
import tabelas.EconomicGroup;
import tabelas.Pessoas;
import tabelas.dao.BankDAO;
import tabelas.dao.ContasDAO;
import tabelas.dao.ContasTipoDAO;
import tabelas.dao.EconomicGroupDAO;
import tabelas.dao.MunicipiosDAO;
import tabelas.dao.PessoasDAO;
import telaPesquisas.jDial_PesquisaBank;
import telaPesquisas.jDial_PesquisaContas;
import telaPesquisas.jDial_PesquisaContasTipo;
import telaPesquisas.jDial_PesquisaEconomicGroup;
import telaPesquisas.jDial_PesquisaMunicipio;
import telaPesquisas.jDial_PesquisaPessoas;

/**
 *
 * @author ferna
 */
public class IntFrm_CadContas extends javax.swing.JInternalFrame {
    
    private Bank bank;
    private ContasTipo contasTipo;
    private Pessoas pessoa;
    private CadMunic municipio;
    private Contas cta;
    private final int INCLUIR = 1;
    private final int ALTERAR = 2;
    private final int EXCLUIR = 3;
    private final int PESQUISA_CONTA = 1;
    private final int PESQUISA_CONTA_ID = 11;
    private final int PESQUISA_BANCO = 2;
    private final int PESQUISA_BANCO_ID = 22;
    private final int PESQUISA_PESSOA = 3;
    private final int PESQUISA_PESSOA_ID = 33;
    private final int PESQUISA_TIPO = 4;
    private final int PESQUISA_TIPO_ID = 44;
    private final int PESQUISA_MUNICIPIO = 5;
    private final int PESQUISA_MUNICIPIO_ID = 55;
    private final int PESQUISA_GRUPO = 6;
    private final int PESQUISA_GRUPO_ID = 66;
    private final int PESQUISA_ECONOMIC_GROUP = 7;
    private final int PESQUISA_ECONOMIC_GROUP_ID = 77;
    private EconomicGroup economicGroup;

    /**
     * Creates new form IntFrm_CadContas
     */
    public IntFrm_CadContas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtId = new tools.JNumberField();
        jLabel2 = new javax.swing.JLabel();
        jTxtIdPessoa = new tools.JNumberField();
        jTxtIdBank = new tools.JNumberField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtAgencia = new javax.swing.JTextField();
        jTxtConta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtIdMunicipio = new tools.JNumberField();
        jTxtNomeMunicipio = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTxtIdTipo = new tools.JNumberField();
        jTxtNomeTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtIdEconomicGroup = new javax.swing.JTextField();
        jTxtNomeEconomicGroup = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTxtNomePessoa = new javax.swing.JTextField();
        jTxtNomeBanco = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jMenuItem1.setText("Copiar");
        jMenuItem1.setEnabled(false);
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Colar");
        jMenuItem2.setEnabled(false);
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Excluir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setClosable(true);
        setTitle("Contas Bancárias");

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jLabel1.setText("Código");

        jTxtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdFocusLost(evt);
            }
        });
        jTxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIdKeyTyped(evt);
            }
        });

        jLabel2.setText("Pessoa");

        jTxtIdPessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdPessoaFocusLost(evt);
            }
        });
        jTxtIdPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIdPessoaKeyTyped(evt);
            }
        });

        jTxtIdBank.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdBankFocusLost(evt);
            }
        });
        jTxtIdBank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIdBankKeyTyped(evt);
            }
        });

        jLabel3.setText("Banco");

        jLabel4.setText("Agência");

        jLabel5.setText("Conta");

        jLabel6.setText("Município");

        jTxtIdMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdMunicipioFocusLost(evt);
            }
        });
        jTxtIdMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIdMunicipioKeyTyped(evt);
            }
        });

        jTxtNomeMunicipio.setEnabled(false);

        jCheckBox1.setText("Encerrada");

        jLabel7.setText("Tipo de Conta");

        jTxtIdTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdTipoFocusLost(evt);
            }
        });
        jTxtIdTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIdTipoKeyTyped(evt);
            }
        });

        jTxtNomeTipo.setEnabled(false);

        jLabel8.setText("Grupo Econômico");

        jTxtIdEconomicGroup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtIdEconomicGroupFocusLost(evt);
            }
        });
        jTxtIdEconomicGroup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIdEconomicGroupKeyTyped(evt);
            }
        });

        jTxtNomeEconomicGroup.setEnabled(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTxtNomePessoa.setEnabled(false);

        jTxtNomeBanco.setEnabled(false);

        jButton9.setText("...");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtConta))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtIdMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeMunicipio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtIdEconomicGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeEconomicGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtIdBank, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeBanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomePessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jTxtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtIdBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jTxtNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtIdMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtIdEconomicGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeEconomicGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)))
        );

        jButton6.setText("Gravar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Limpar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        tools.ClearFields.ClearFields(jPanel1);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        gravaDados(EXCLUIR);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        incluiPesquisa(PESQUISA_PESSOA);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTxtIdPessoaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdPessoaFocusLost
        if ("".equals(jTxtNomePessoa.getText())) {
            incluiPesquisa(PESQUISA_PESSOA_ID);
        }
    }//GEN-LAST:event_jTxtIdPessoaFocusLost

    private void jTxtIdPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdPessoaKeyTyped
        jTxtNomePessoa.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdPessoaKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        incluiPesquisa(PESQUISA_BANCO);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTxtIdBankKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdBankKeyTyped
        jTxtNomeBanco.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdBankKeyTyped

    private void jTxtIdBankFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdBankFocusLost
        if ("".equals(jTxtNomeBanco.getText())) {
            incluiPesquisa(PESQUISA_BANCO_ID);
        }
    }//GEN-LAST:event_jTxtIdBankFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        incluiPesquisa(PESQUISA_MUNICIPIO);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtIdMunicipioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdMunicipioKeyTyped
        jTxtNomeMunicipio.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdMunicipioKeyTyped

    private void jTxtIdMunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdMunicipioFocusLost
        if ("".equals(jTxtNomeMunicipio.getText())) {
            incluiPesquisa(PESQUISA_MUNICIPIO_ID);
        }
    }//GEN-LAST:event_jTxtIdMunicipioFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        incluiPesquisa(PESQUISA_TIPO);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtIdTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdTipoKeyTyped
        jTxtNomeTipo.setText("");
    }//GEN-LAST:event_jTxtIdTipoKeyTyped

    private void jTxtIdTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdTipoFocusLost
        if ("".equals(jTxtNomeTipo.getText())) {
            incluiPesquisa(PESQUISA_TIPO_ID);
        }
    }//GEN-LAST:event_jTxtIdTipoFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if ("".equals(jTxtId.getText())) {
            
            gravaDados(INCLUIR);
        } else {
            
            gravaDados(ALTERAR);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTxtIdEconomicGroupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdEconomicGroupKeyTyped
        jTxtNomeEconomicGroup.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdEconomicGroupKeyTyped

    private void jTxtIdEconomicGroupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdEconomicGroupFocusLost
        if ("".equals(jTxtNomeEconomicGroup.getText())) {
            incluiPesquisa(PESQUISA_ECONOMIC_GROUP_ID);
        }
    }//GEN-LAST:event_jTxtIdEconomicGroupFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        incluiPesquisa(PESQUISA_ECONOMIC_GROUP);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdKeyTyped
        String id = jTxtId.getText();
        tools.ClearFields.ClearFields(jPanel1);
        jTxtId.setText(id);
    }//GEN-LAST:event_jTxtIdKeyTyped

    private void jTxtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIdFocusLost
        if ("".equals(jTxtIdBank.getText())) {
            incluiPesquisa(PESQUISA_CONTA_ID);
        }
    }//GEN-LAST:event_jTxtIdFocusLost

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        incluiPesquisa(PESQUISA_CONTA);
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTxtAgencia;
    private javax.swing.JTextField jTxtConta;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtIdBank;
    private javax.swing.JTextField jTxtIdEconomicGroup;
    private javax.swing.JTextField jTxtIdMunicipio;
    private javax.swing.JTextField jTxtIdPessoa;
    private javax.swing.JTextField jTxtIdTipo;
    private javax.swing.JTextField jTxtNomeBanco;
    private javax.swing.JTextField jTxtNomeEconomicGroup;
    private javax.swing.JTextField jTxtNomeMunicipio;
    private javax.swing.JTextField jTxtNomePessoa;
    private javax.swing.JTextField jTxtNomeTipo;
    // End of variables declaration//GEN-END:variables

    public void recebeBank(Bank m) {
        this.bank = m;
    }
    
    public void recebeContaTipo(ContasTipo m) {
        this.contasTipo = m;
    }
    
    public void recebePessoa(Pessoas p) {
        System.out.println("Recebendo Pessoa: " + p);
        this.pessoa = p;
    }
    
    public void recebeMunicipio(CadMunic m) {
        this.municipio = m;
    }
    
    public void recebeConta(Contas c) {
        this.cta = c;
    }
    
    private void gravaDados(int action) {
        try {
            if (action > INCLUIR && jTxtId.getText().equals("")) {
                throw new SQLException("Informe um cadastro para continuar.");
            }
            
            Contas ct = new Contas();
            try {
                ct.setId(Integer.parseInt(jTxtId.getText()));
            } catch (Exception e) {
                ct.setId(0);
            }
            ct.setAgencia(jTxtAgencia.getText());
            ct.setConta(jTxtConta.getText());
            ct.setFinished(jCheckBox1.isSelected());
            
            try {
                ct.setPessoa(new Pessoas(Integer.parseInt(jTxtIdPessoa.getText())));
                ct.setBank(new Bank(Integer.parseInt(jTxtIdBank.getText())));
                ct.setCidade(new CadMunic(Integer.parseInt(jTxtIdMunicipio.getText())));
                ct.setAccount(new ContasTipo(Integer.parseInt(jTxtIdTipo.getText())));
                ct.setEconomicGroup(new EconomicGroup(Integer.parseInt(jTxtIdEconomicGroup.getText())));
            } catch (Exception e) {
                throw new UnsupportedOperationException("Preencha todos os campos para continuar!");
            }
            
            ContasDAO ctDAO = new ContasDAO();
            
            switch (action) {
                case INCLUIR:
                    ctDAO.create(ct);
                    jTxtId.setText(ct.getId() + "");
                    
                    break;
                case ALTERAR:
                    ctDAO.update(ct);
                    break;
                
                case EXCLUIR:
                    ctDAO.delete(ct);
                    
                    break;
            }
            conn.ConexaoMySQL.finalizarTransacao(true);
            tools.DefaultMsg.saveDataSuccessfull();
            tools.ClearFields.ClearFields(jPanel1);
            
        } catch (Exception e) {
            conn.ConexaoMySQL.finalizarTransacao(false);
            tools.DefaultMsg.errorMsg(e.getMessage());
        }
    }
    
    private void incluiPesquisa(int x) {
        switch (x) {
            case PESQUISA_CONTA:
                jDial_PesquisaContas dContas = new jDial_PesquisaContas(this, true);
                dContas.setVisible(true);
                
                incluiPesquisa(cta);
                
                break;
            
            case PESQUISA_CONTA_ID:
                cta = null;
                if (!"".equals(jTxtId.getText())) {
                    ContasDAO ctDAO = new ContasDAO();
                    incluiPesquisa(ctDAO.getContas(Integer.parseInt(jTxtId.getText())));
                }
                break;
            
            case PESQUISA_ECONOMIC_GROUP:
                jDial_PesquisaEconomicGroup dEcon = new jDial_PesquisaEconomicGroup(this, true);
                dEcon.setVisible(true);
                
                incluiPesquisa(economicGroup);
                break;
            
            case PESQUISA_ECONOMIC_GROUP_ID:
                economicGroup = null;
                if (!"".equals(jTxtIdEconomicGroup.getText())) {
                    EconomicGroupDAO ecDAO = new EconomicGroupDAO();
                    incluiPesquisa(ecDAO.getEconomicGroup(Integer.parseInt(jTxtIdEconomicGroup.getText())));
                }
                
                break;
            
            case PESQUISA_TIPO_ID:
                contasTipo = null;
                if (!"".equals(jTxtIdTipo.getText())) {
                    ContasTipoDAO tDAO = new ContasTipoDAO();
                    incluiPesquisa(tDAO.getContasTipo(Integer.parseInt(jTxtIdTipo.getText())));
                }
                break;
            
            case PESQUISA_TIPO:
                contasTipo = null;
                jDial_PesquisaContasTipo dTipo = new jDial_PesquisaContasTipo(this, true);
                dTipo.setVisible(true);
                
                incluiPesquisa(contasTipo);
                
                break;
            
            case PESQUISA_MUNICIPIO_ID:
                municipio = null;
                if (!"".equals(jTxtIdMunicipio.getText())) {
                    MunicipiosDAO mDAO = new MunicipiosDAO();
                    incluiPesquisa(mDAO.getMunicipio(Integer.parseInt(jTxtIdMunicipio.getText())));
                }
                break;
            
            case PESQUISA_MUNICIPIO:
                municipio = null;
                
                jDial_PesquisaMunicipio dMun = new jDial_PesquisaMunicipio(this, true);
                dMun.setVisible(true);
                
                incluiPesquisa(municipio);
                
                break;
            
            case PESQUISA_BANCO:
                bank = null;
                
                jDial_PesquisaBank pBank = new jDial_PesquisaBank(this, true);
                pBank.setVisible(true);
                
                incluiPesquisa(bank);
                
                break;
            case PESQUISA_BANCO_ID:
                bank = null;
                if (!"".equals(jTxtIdBank.getText())) {
                    BankDAO bDAO = new BankDAO();
                    incluiPesquisa(bDAO.getBank(Integer.parseInt(jTxtIdBank.getText())));
                }
                break;
            case PESQUISA_PESSOA:
                
                pessoa = null;
                
                jDial_PesquisaPessoas dPessoa = new jDial_PesquisaPessoas(this, true);
                dPessoa.setVisible(true);
                
                incluiPesquisa(pessoa);
                
                break;
            case PESQUISA_PESSOA_ID:
                pessoa = null;
                if (!"".equals(jTxtIdPessoa.getText())) {
                    PessoasDAO pDAO = new PessoasDAO();
                    incluiPesquisa(pDAO.getPessoas(Integer.parseInt(jTxtIdPessoa.getText())));
                }
                
                break;
        }
        
    }
    
    private void incluiPesquisa(CadMunic mun) {
        
        jTxtIdMunicipio.setText("");
        jTxtNomeMunicipio.setText("");
        
        try {
            if (mun.getId() == null) {
                throw new UnsupportedOperationException();
            }
            
            jTxtIdMunicipio.setText(mun.getId() + "");
            jTxtNomeMunicipio.setText(mun.getNome() + " - " + mun.getUf());
            
        } catch (Exception e) {
            
        }
        
    }
    
    private void incluiPesquisa(Pessoas pessoa) {
        jTxtIdPessoa.setText("");
        jTxtNomePessoa.setText("");
        
        try {
            
            if (pessoa.getId() == null) {
                throw new UnsupportedOperationException();
            }
            
            jTxtIdPessoa.setText(pessoa.getId() + "");
            jTxtNomePessoa.setText(pessoa.getNome());
            
        } catch (Exception e) {
            
        }
    }
    
    private void incluiPesquisa(Bank bank) {
        jTxtIdBank.setText("");
        jTxtNomeBanco.setText("");
        
        try {
            
            if (bank.getId() == null) {
                throw new UnsupportedOperationException();
            }
            
            jTxtNomeBanco.setText(bank.getTitle());
            jTxtIdBank.setText(bank.getId() + "");
        } catch (Exception e) {
            
        }
        
    }
    
    private void incluiPesquisa(ContasTipo ct) {
        jTxtIdTipo.setText("");
        jTxtNomeTipo.setText("");
        
        try {
            
            if (ct.getId() == null) {
                throw new UnsupportedOperationException();
            }
            jTxtIdTipo.setText(ct.getId() + "");
            jTxtNomeTipo.setText(ct.getTitle());
        } catch (Exception e) {
            
        }
        
    }
    
    public void recebeEconomicGroup(EconomicGroup m) {
        this.economicGroup = m;
    }
    
    private void incluiPesquisa(EconomicGroup economicGroup) {
        jTxtIdEconomicGroup.setText("");
        jTxtNomeEconomicGroup.setText("");
        try {
            
            if (economicGroup.getId() == null) {
                throw new UnsupportedOperationException();
            }
            jTxtIdEconomicGroup.setText(economicGroup.getId() + "");
            jTxtNomeEconomicGroup.setText(economicGroup.getTitle());
            
        } catch (Exception e) {
            
        }
    }
    
    private void incluiPesquisa(Contas contas) {
        tools.ClearFields.ClearFields(jPanel1);
        
        try {
            if (contas.getId() == null) {
                throw new UnsupportedOperationException();
            }
            
            jTxtId.setText(contas.getId() + "");
            jTxtIdPessoa.setText(contas.getPessoa().getId() + "");
            jTxtNomePessoa.setText(contas.getPessoa().getNome());
            jTxtIdBank.setText(contas.getBank().getId() + "");
            jTxtNomeBanco.setText(contas.getBank().getTitle());
            jTxtAgencia.setText(contas.getAgencia());
            jTxtConta.setText(contas.getConta());
            jTxtIdMunicipio.setText(contas.getCidade().getId() + "");
            jTxtNomeMunicipio.setText(contas.getCidade().getNome());
            jTxtIdTipo.setText(contas.getAccount().getId() + "");
            jTxtNomeTipo.setText(contas.getAccount().getTitle());
            jTxtIdEconomicGroup.setText(contas.getEconomicGroup().getId() + "");
            jTxtNomeEconomicGroup.setText(contas.getEconomicGroup().getTitle());
            jCheckBox1.setSelected(contas.getFinished());
            
        } catch (Exception e) {
            
            
        }
    }
}
